create table if not exists public.staff_access_audit (
  id bigint generated by default as identity primary key,
  actor_clerk_user_id text not null,
  target_clerk_user_id text not null,
  previous_role text,
  new_role text,
  changed_at timestamptz not null default now(),
  constraint staff_access_audit_previous_role_check
    check (previous_role is null or previous_role in ('admin', 'staff')),
  constraint staff_access_audit_new_role_check
    check (new_role is null or new_role in ('admin', 'staff'))
);

create index if not exists staff_access_audit_target_time_idx
  on public.staff_access_audit (target_clerk_user_id, changed_at desc);

create index if not exists staff_access_audit_actor_time_idx
  on public.staff_access_audit (actor_clerk_user_id, changed_at desc);

alter table public.staff_access_audit enable row level security;